### PR TITLE
More config paths

### PR DESCRIPTION
**Pull request by rtissera**

### CODE REVIEW

**Comment by rtissera** [comment]
@djyt any chance to see this one merged ?
It would help us batocera as we are integrating this core officially in upcoming release :)

**Comment by djyt** [comment]
Hello. Sorry for the delay. 

I am going to support this very soon (like in a few days). It will be done as part of the config.xml file - as opposed to the cmake file. 

Chris.

**Comment by rtissera** [comment]
Hello,

Amazing news, no problem for delay.

Stay safe !

Le mer. 3 mars 2021 à 12:42, reassembler <notifications@github.com> a
écrit :

**Comment by djyt** [comment]
OK, and it's in now :) Check the config.xml for configuration details.

**Pull request closed without merging**
