### PR TITLE
Load gamecontrollerdb.txt mappings

### PR DESCRIPTION
**Pull request by DanTheMan827**

### CODE REVIEW

**Comment by djyt** [comment]
I wasn't actually aware of this - looks handy and I've merged the changes. Anything else I should be aware of?!

**Comment by DanTheMan827** [comment]
Not that I can think of

**Comment by djyt** [comment]
Cool. I've made a couple of additional changes, which I *think* make this work a little better:

1/ Include the latest gamecontrollerdb.txt in the res directory.

2/ Call SDL_GameControllerAddMappingsFromFile AFTER sdl initalizes. It seems to pull a smaller sub-set of controllers, which I'm guessing is based upon what it's already discovered during initialization.

3/ I've added the location of the "res" directory to the config.xml so this can be changed. This is potentially useful on Linux based systems.

**Comment by DanTheMan827** [comment]
You can't add the mappings after initializing the controllers otherwise the controllers connected will only use the mappings included with SDL2

**Comment by djyt** [comment]
OK, that's somewhat annoying, but I'll revert that.

**Comment by DanTheMan827** [comment]
If you want, I think you could always remove SDL_JOYSTICK from the `SDL_Init` line that you have, move the code to load the mappings, and then init the joystick separately, but that's your call.

**Comment by djyt** [comment]
Nah I think we're good. Next step will be implementing digital menu support for joysticks. Initially, I always presumed people would have a keyboard available... in somewhat of a "640k will be enough" design decision

**Comment by DanTheMan827** [comment]
So I found a bug... because of the fact that you read everything as a joypad, you're effectively ignoring the mappings and instead getting the raw input values unmapped.

#77

**Pull request merged**
